---
title: "Session 6"
author: "BAO YEN HO"
date: "21/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Loading hotel booking
```{r}
hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv')
rm(list=ls())

```

```{r}
install.packages("skimr")
library(skimr)

```

```{r}
hotels%>%head()

hotels %>%distinct(hotel)

hotels%>%count(hotel)

hotels%>%skim()

hotels%>%count(arrival_date_year)

hotels%>%mutate(arrival_date_year=as_factor(arrival_date_year))%>% #Change variable to factor so we can group variables
group_by(arrival_date_year)%>%
  count(is_canceled, sort=TRUE)

```


```{r}
summary(hotels)
```

Average number of days in `lead_time` per type of hotel

```{r}
hotels%>%
  group_by(hotel)%>%
  summarise(average_lead_time=mean(lead_time))%>%
  ungroup()
```

Data visualization of cancelations per type of hotel

```{r}
hotels%>%
  ggplot(
    aes(is_canceled)
  )+
  geom_histogram()+
  facet_wrap(vars(hotel))
```

Calculate the maximun `lead_time`
```{r}
hotels %>%
  group_by(hotel)%>%
  mutate(max_lead_time=max(lead_time))%>%
  count(hotel, max_lead_time)%>%
  ungroup()

  
  
  
```

