---
title: "Session 7"
author: "BAO YEN HO"
date: "25/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
#install.packages("lubridate")
library(lubridate)
```

 Dataset's information: https://github.com/rfordatascience/tidytuesday/tree/master/data/2020/2020-02-11

**Explore data types**

```{r}
hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv')
summary(hotels)
skim(hotels)
#`hotel` should be categorical variable, `lead_time`: continuous variable, `arrival_date_year`: should not be as *double*, `arrival_date_month`: character

```


**Recording factor**
```{r}
hotels$hotel<-as_factor(hotels$hotel)

#change to factor for arrival_date_year and arrival_date_month and country

hotels$arrival_date_year<-as_factor(hotels$arrival_date_year)
hotels$arrival_date_month<-as_factor(hotels$arrival_date_month)
hotels$country<-as_factor(hotels$country)
skim(hotels)
```

```{r}
parse_number("euro1,000")
```

```{r}
#how can we refactor several variables
cols <- c("market_segment", "distribution_channel","customer_type", "deposit_type","arrival_date_year")
hotels[cols]<- lapply(hotels[cols] , factor)
skim(hotels)
```


##using case_when
```{r}

#Create a new variable Family. The value equals "family" if children are more than 0, "couple" otherwise

hotels<-hotels%>%
  mutate(family=case_when(children>0~"family", babies>0~"family",TRUE~"couple"))

```

```{r}
hotels<-hotels%>%
  mutate(family_new =
           case_when(children > 0 ~ TRUE,
                     babies > 0 ~ TRUE,
                     TRUE ~ FALSE))

```

```{r}
hotel_stays <- hotels %>%
  filter(is_canceled == 0) %>%
  mutate(
    children = case_when(
      children + babies > 0 ~ "children",
      TRUE ~ "none"
    ),
    required_car_parking_spaces = case_when(
      required_car_parking_spaces > 0 ~ "parking",
      TRUE ~ "none"
    )
  ) %>%
  select(-is_canceled, -reservation_status, -babies)
```

**Basic Data wrangling**
```{r}
#install.packages("scales")

```


```{r}
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month,
    levels = month.name
  )) %>%
  count(hotel, arrival_date_month, children, sort=TRUE)%>%
  group_by(hotel, children) %>%
  mutate(proportion = n/sum(n))%>%
  ggplot(aes(arrival_date_month, proportion, fill = children)) +
  geom_col(position = "dodge", color= "blue") 
  
  
#Experiement by using "color" instead of "fill" and removing this argument altogether
#change "position" argument

```
```{r}
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month,
    levels = month.name
  )) %>%
  count(hotel, arrival_date_month, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(arrival_date_month, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::percent_format())
```

  **Faceting**

```{r}
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month,
    levels = month.name
  )) %>%
  count(hotel, arrival_date_year, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(arrival_date_year, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  #facet_wrap(~hotel, nrow = 2)
  facet_wrap(~arrival_date_year)
```

```{r}
hotel_stays %>%
  mutate(arrival_date_month = factor(arrival_date_month,
    levels = month.name
  )) %>%
  count(hotel, arrival_date_month, children) %>%
  group_by(hotel, children) %>%
  mutate(proportion = n / sum(n)) %>%
  ggplot(aes(arrival_date_month, proportion, fill = children)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  facet_wrap(~hotel, nrow = 2) +
  labs(
    x = NULL,
    y = "Proportion of hotel stays",
    fill = NULL
  )
```

